### ISSUE TITLE
Define in README.md what happens if a time string is invalid

### ISSUE THREAD

**Issue by axelpale** [philbooth/css-time.js#2]
Without this tiny piece of documentation it is inconvenient for a developer to use the methods. If css-time is used as a part of another library, the time parameter probably comes from unknown code. Therefore developers want to know should they validate the parameter before using the methods or should they expect an error to be thrown. Of course a dev can read the code but relying on that kind of thrashes the purpose of documentation in the first place.

**Comment by philbooth** [comment]
Yep, fair point. Will update.

**Comment by axelpale** [comment]
Great, thanks!

**Comment by philbooth** [comment]
Done. :)
